version: 2.1

workflows:
  legacy-database-testing-cron:
    # cron
    # Test the original `circleci/` convenience images
    triggers:
      - schedule:
          # Nightly at 10:00 UTC
          cron: "0 10 * * *"
          filters:
            branches:
              only: master
    jobs:
      - legacy-test-mariadb:
          version: "10.3"
  legacy-database-testing:
    # always runs
    # Test the original `circleci/` convenience images
    jobs:
      - legacy-test-mariadb:
          version: "10.1"
          name: "MariaDB v10.1"
      - legacy-test-mariadb:
          version: "10.2"
          name: "MariaDB v10.2"
      - legacy-test-mariadb:
          version: "10.3"
          name: "MariaDB v10.3"
      - legacy-test-mariadb:
          version: "10.4"
          name: "MariaDB v10.4"
      #- legacy-test-mysql
      #- legacy-test-postgresql
      #- legacy-test-mongodb
      #- legacy-test-dynamodb

jobs:
  legacy-test-mariadb:
    parameters:
      version:
        description: "MariaDB version to test."
        type: string
    docker:
      - image: cimg/base:stable
      - image: circleci/mariadb:<< parameters.version >>
    steps:
      - run:
          name: "Install MariaDB Client"
          command: apt-get update && apt-get install -y mysql-client
      - run:
          name: "Very MariaDB Version"
          command: mysql -h 127.0.0.1 -e 'SELECT VERSION();' | grep "<< parameters.version >>"
      - run:
          name: "Try Creating a New Database"
          command: mysql -h 127.0.0.1 -e 'CREATE DATABASE my_test_database;'
